server:
  port: 8002
mybatis:
  config-location: classpath:mybaties/mybatis-config.xml
  mapper-locations: classpath:mybaties/mapper/**/*.xml
  type-aliases-package: com.myself.springcloud.entities  #所有实体类所在包
spring:
  application:
    name: microservicecloud-dept      #对外暴露的微服务的名字
  datasource:
    url: jdbc:mysql://192.168.1.233/clouddb02?serverTimezone=GMT%2B8&allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 1qaz@WSX
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    dbcp2:
      min-idle: 5       #数据库连接池最小链接数
      initial-size: 5     #初始化连接数
      max-total: 5        #最大连接数
      max-wait-millis: 200    #等待链接获取的链接时间
eureka:
  client: #客户端注册进eureka服务列表内
    service-url:
      #defaultZone: http://localhost:7001/eureka
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: microservicecloud-dept8002  #自定义服务名称信息
    prefer-ip-address: true     #访问路径可以显示IP地址

info:
  app.name: myself-microservicecloud
  company.name: www.atguigu.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$